name: notes
description: >
  Note creation and management app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.10.5 <4.0.0'

dependencies:
  #Flutter SDK
  flutter:
    sdk: flutter

  #BLoC
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5

  #Persisting
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3

  #Navigation
  go_router: ^14.1.3

  #Codegen
  freezed_annotation: ^2.4.1

  #Dependency Injection
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
