name: notes
description: >
  Note creation and management app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.10.5 <4.0.0'

dependencies:
  #Flutter SDK
  flutter:
    sdk: flutter

  #BLoC
  flutter_bloc: ^8.1.5

  #Persisting
  sqlite3_flutter_libs: ^0.5.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
